name: Minify Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      # Auto-commit to repository
      - uses: ajaykpandit/minification-testing@v1.0.1
        with:
          commit_message: Minify source code
